name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"

      - name: Instalar dependencias
        run: npm ci

      - name: Instalar Navegadores de Playwright
        run: npx playwright install --with-deps chromium # Installs just Chromium for faster CI execution

      - name: Ejecutar pruebas de Playwright
        run: npx playwright test

      - name: Subir Reporte HTML y Evidencias
        uses: actions/upload-artifact@v4
        if: always() # Guarda el reporte siempre, incluso si fallan los tests
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30 # Keep the reports for 30 days
